services:
  mongodb:
    image: mongo:7.0
    container_name: vaas-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: template_engine
    volumes:
      - mongo_data:/data/db

  kafka:
    image: apache/kafka:3.7.0
    container_name: vaas-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Configuração de 2 caminhos: EXTERNAL (p/ seu PC) e INTERNAL (p/ o Kafdrop)
      KAFKA_LISTENERS: 'EXTERNAL://:9092,INTERNAL://:29092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:9092,INTERNAL://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: vaas-kafdrop
    ports:
      - "9000:9000"
    environment:
      # Kafdrop fala com o Kafka pela rede interna do Docker (porta 29092)
      KAFKA_BROKERCONNECT: kafka:29092
    depends_on:
      - kafka

volumes:
  mongo_data: